version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
  docker-build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push to DockerHub
          command: |
            docker build -t project/node-app:latest .
            echo "$DOCKER_PASS" | docker login -u vagusatwik7@gmail.com --password-stdin
            docker push project/node-app:latest
workflows:
  build_and_dockerize:
    jobs:
      - build
      - docker-build:
          requires:
            - build
